name: Node.js Selenium Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: Install Node.js dependencies
        run: npm install

      - name: Prepare artifacts
        run: |
          ls 
          tar -czvf www-build.tar.gz package.json src tests
          ls -l

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: www-build
          path: www-build.tar.gz

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: www-build

      - name: Extract artifacts
        run: tar -xzvf www-build.tar.gz

      - name: List files for debugging
        run: ls -ltra

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Start Node.js server
        run: |
          nohup node src/server.js &  # Start the server in the background
          sleep 5  # Give the server some time to start

      - name: Verify server is running
        run: |
          curl -f http://localhost:3000 || { echo "Server failed to start"; exit 1; }

      - name: Wait for Selenium server to be up
        run: |
          for i in {1..10}; do
            curl -s $SELENIUM_HOST && break || sleep 3
          done

      - name: Run Selenium tests
        run: node tests/SeleniumTest.mjs github